export enum TipoItemAtividadeEnum {
    UNICA_ESCOLHA = "UNICA_ESCOLHA",
    MULTIPLAS_ESCOLHAS = "MULTIPLAS_ESCOLHAS",
    DISSERTATIVO = "DISSERTATIVO",
    NUMERICO = "NUMERICO",
    FEEDBACK = "FEEDBACK"
}
